database:
  show-cities: false
  download-if-missing: true
  download-url: http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz
  download-url-city: http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
  update:
    enable: true
    by-every-x-days: 30
show-on-login: true
show-on-whois: true
enable-locale: true
